name: add to project community

on:
  issues:
    types:
      - opened
      - reopened

permissions:
  repository-projects: write

jobs:
  add-to-project:
    secrets:
      SENZING_GITHUB_ACCESS_TOKEN: ${{ secrets.SENZING_GITHUB_ACCESS_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/add-to-project.yaml@v2
    with:
      classic: true
      project-number: ${{ vars.SENZING_PROJECT_COMMUNITY }}
      org: ${{ vars.SENZING_GITHUB_ACCOUNT_NAME }}
